version: '3'

services:
  postgres:
    image: postgres:14
#    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: crypto-analyzer
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto
    ports:
      - "5432:5432"
