server:
  port: 8010
#  error:
#    whitelabel:
#      enabled: false

spring:
  application:
    name: portfolio-service
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto-analyzer
    driver-class-name: org.postgresql.Driver
    username: crypto
    password: crypto
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
  main:
    banner-mode: off
