name: Crypto Analyzer CI/CD

on:
  push:
    branches:
      - 'feature-*'
  pull_request:
    branches:
      - '*'

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Copying files on gitlab-runner server
        env:
          USERNAME: ${{ secrets.USERNAME }}
          IP_ADDRESS: ${{ secrets.IP_ADDRESS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          scp -i $SSH_PRIVATE_KEY -r . $USERNAME@$IP_ADDRESS:/home

      - name: Creating .evn file
        env:
          USERNAME: ${{ secrets.USERNAME }}
          IP_ADDRESS: ${{ secrets.IP_ADDRESS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i $SSH_PRIVATE_KEY $USERNAME@$IP_ADDRESS << EOF
            cd /home/crypto-analyzer/docker
            cat .env << EOF
            TAG=latest
            PORTFOLIO_SERVICE_EXTERNAL_PORT=9000
            PORTFOLIO_SERVICE_INTERNAL_PORT=8080
            POSTGRES_DB=crypto-analyzer
            POSTGRES_USER=crypto
            POSTGRES_PASSWORD=crypto
            POSTGRES_EXTERNAL_PORT=5435
            POSTGRES_INTERNAL_PORT=5432
            EOF
          EOF

      - name: Starting Docker Compose image
        env:
          USERNAME: ${{ secrets.USERNAMEE }}
          IP_ADDRESS: ${{ secrets.IP_ADDRESS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i $SSH_PRIVATE_KEY $USERNAME@$IP_ADDRESS << EOF
            cd /home/crypto-analyzer/docker
            docker-compose down || true
            docker-compose up --build -d
          EOF
