name: Crypto Analyzer CI/CD

on:
  push:
    branches:
      - 'feature-*'
  pull_request:
    branches:
      - '*'

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Creating project folder
        run: mkdir -p ./crypto-analyzer/docker

      - name: Copying files on gitlab-runner server
        env:
          USERNAME: ${{ secrets.USERNAME }}
          IP_ADDRESS: ${{ secrets.IP_ADDRESS }}
        run: |
          scp -i private_key -r . $USERNAME@$IP_ADDRESS:/crypto-analyzer/docker

      - name: Starting Docker Compose image
        env:
          USERNAME: ${{ secrets.USERNAMEE }}
          IP_ADDRESS: ${{ secrets.IP_ADDRESS }}
        run: |
          ssh -i private_key $USERNAME@$IP_ADDRESS << EOF
            cd /crypto-analyzer/docker
            docker-compose down || true
            docker-compose up --build -d
          EOF
